[package]
name = "mkv-renmame"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
matroska = "0.22.0"
time = { version = "0.3.20", features = ["parsing"] }
xflags = "0.3.1"
